Include ~/.colima/ssh_config

Host *
  IdentityAgent "~/Library/Group Containers/2BUA8C4S2C.com.1password/t/agent.sock"

Host github-pvt
  HostName github.com
  IdentityAgent none
  IdentitiesOnly yes
  IdentityFile ~/.ssh/id_ecdsa_sk_bio
  IdentityFile ~/.ssh/id_ecdsa_sk
  ControlMaster auto

Host oldmac
  HostName 192.168.1.190
  User flaviocaetano
  IPQoS throughput

Host pi3
  HostName pi3.local
  User flavio

Host windows
  HostName 192.168.1.113
  User flavio
